### ISSUE TITLE
Fails to recognize certain regex strings

### ISSUE THREAD

**Issue by infininight** [textmate/perl.tmbundle#1]
Sample where it breaks:

    if (/ Check \s (Mate)/x)

**Comment by y** [comment]
I can't believe github uses this for syntax highlighting ([linguist](http://github.com/github/linguist)) when such common syntax is broken for 5+ years.

**Comment by infininight** [comment]
@y All of the language grammars are open source and we happily accept pull requests to fix issues.

**Comment by Fank** [comment]
@infininight i'm currently fixing/improving https://github.com/atom/language-perl, you could copy a lot of changes back to your repo, i also got a nice solution for this issue, which is attached above.
BTW if you wan't you could add all highlight issues you find in your repo, and ill attach commits ive done in atom perl language repo, so we can improve both.

**Comment by infininight** [comment]
@Fank Thanks for the note. I've back ported all of the recent changes now, believe the two are now in sync again. The different formats and escaping rules make it very labor intensive to do, at least with the more complicated commits.

I am now watching the atom fork so I should get notified of changes now, will try to keep them in sync but feel free to send me a message or @ msg if you want my attention.

Comparing the two I did see one commit you should port the other direction: 8f62f3c458cacba3152bfedcc971735a0a5d61b1 This avoids giving whitespace surrounding a constant as a constant as well.

Thanks for the work. :)
