### ISSUE TITLE
Properties named 'q' trigger the q quote highlighting

### ISSUE THREAD

**Issue by pchaigno** [textmate/perl.tmbundle#14]
Originally reported by @darkliquid at atom/language-perl#7:

> In the following example, the portion of the code from q; until the next ; is erroneously highlighted as a quoted string - specifically the 2nd print keyword is highlighted as a string instead of like the other prints.

```perl
sub q() {}
my $test = {};
bless $test;
print $test->q;
# this is some code that should not be string highlighted
print "end";
```

(This TextMate bundle is used by GitHub to highlight Perl code in files and snippets.)

**Comment by infininight** [comment]
In perl we only match individual parts of syntax, with this rule basically being `q` followed by absolutely anything it can be easy to get false positives.

I came up with two work arounds: The first is to not let q-strings follow the -> operator the other is to not allow `;` as a delimiter. Any opinion on which would be the better solution?

**Comment by darkliquid** [comment]
My instinct is to not process `q` after `->`, the reason being that this will never be a q-string, while a `;` delimiter can be correct usage.
