### ISSUE TITLE
Heredoc fixes & improvements

### ISSUE THREAD

**Issue by Fank** [textmate/perl.tmbundle#15]
@infininight https://github.com/atom/language-perl/pull/32

**Comment by infininight** [comment]
Pulled, thanks!

@Fank There is a typo in your commit:

https://github.com/atom/language-perl/blob/master/grammars/perl.cson#L853

`text.js.embedded.perl` should be `source.js.embedded.perl`

**Comment by Fank** [comment]
Dawm thanks
