### ISSUE TITLE
Ignore whitespace in comparison operator

### ISSUE THREAD

**Issue by Fank** [textmate/perl.tmbundle#16]
https://github.com/atom/language-perl/commit/fb6b7c683902cb005ee870ab222d6aa38a3b59d6

![compare](https://cloud.githubusercontent.com/assets/1900106/6779510/007b5808-d15d-11e4-8d36-8bd863eb5772.png)

**Comment by infininight** [comment]
Ported in b1f624ee3a3825f6dd1233f6379cc4d0deaac4e0, thanks.
