### ISSUE TITLE
Syntax highlighting of the <> operator (glob) is broken.

### ISSUE THREAD

**Issue by SaberUK** [textmate/perl.tmbundle#9]
Example: `<foo/bar/baz.*>`

Screenshot: http://i.imgur.com/hOpWSd9.png

**Comment by Fank** [comment]
@infininight https://github.com/atom/language-perl/pull/39

**Comment by chrstphrchvz** [comment]
Is this issue still present? I could not reproduce it with the March 2018 Perl bundle:
![screen shot 2018-11-11 at 4 59 55 pm](https://user-images.githubusercontent.com/7941193/48319404-3ed7f280-e5d3-11e8-97de-ab20185c7f61.png)

**Comment by SaberUK** [comment]
Yes, this is fixed now. Thanks!
